### ISSUE TITLE
Text Part Contains Surrounding HTML elements

### ISSUE THREAD

**Issue by ronnieoverby** [robinvanderknaap/RazorMailMessage#3]
When supplying a text template, the rendered text has HTML elements that surround the text.

**Comment by robinvanderknaap** [comment]
I'm using the library myself, but haven't seen this behavior.
Could you check the following things:
- Filename of text template follows convention. yourtemplatename.text.cshtml
- Text template is marked as embedded resource
- You don't have any html elements in your text template
- The shared layout of the text template does not contain any html elements

**Comment by ronnieoverby** [comment]
All true.

**Comment by robinvanderknaap** [comment]
I've just checked an email generated with razormail, no html elements.
Can you send me the email source? Also, maybe the templates, so I can have a closer look?
Also, with what kind of tool are you inspecting the email?

I personally use [smpt4dev](https://smtp4dev.codeplex.com/), this is a simple smtp server, which does not actually send the email, but retains the mails, so you can inspect them.

**Comment by ronnieoverby** [comment]
Im taking the base 64 of the text part directly from the email and decoding
it.

**Comment by robinvanderknaap** [comment]
Weird, I did the same, no html elements. I don’t know where they are coming from. I need more info, like the templates, to solve this.

**Comment by robinvanderknaap** [comment]
How did you obtain the text part?

**Comment by ronnieoverby** [comment]
I'll send when i have a chance

**Comment by ronnieoverby** [comment]
I've discovered the problem. It's not the fault of RazorMailMessage, but another library: https://github.com/milkshakesoftware/PreMailer.Net
